import mongoose from 'mongoose'
import { Entry, Category } from './db.js'

//Refactor: Since schema was changed
// const categories = [
//     { name: 'Food' },
//     { name: 'Gaming' },
//     { name: 'Coding' },
//     { name: 'Other' }
// ]

// However, this approach of embedding entries into categories is not ideal
// since we have a route that gets all entries.
// If we use this approach, we have to iterate all entries in categories,
// get the entry in each category and combine all of the entries in one array.
// This takes complex steps to implement.

// Refer to part 2 directory for the continuation

const categories = [
    { 
        name: 'Food',
        entries: [ // Entries will also have their own id generated by mongoDB after seeding to the db.
            { content: 'Pizza is yummy!'}
        ] 
    },
    { 
        name: 'Gaming',
        entries: [
            { content: 'War. War never changes'}
        ] 
    },
    { 
        name: 'Coding',
        entries: [
            { content: 'Coding is fun!'}
        ] 
    },
    { 
        name: 'Other',
        entries: [] 
    }
]

// const entries = [
//     { id: 1, category: 'Food', content: 'Pizza is yummy!' },
//     { id: 2, category: 'Coding', content: 'Coding is fun!' },
//     { id: 3, category: 'Gaming', content: 'War. War never changes.' },
// ]

// Refactor: Nested inside the categories
// const entries = [
//     { category: 'Food', content: 'Pizza is yummy!' },
//     { category: 'Coding', content: 'Coding is fun!' },
//     { category: 'Gaming', content: 'War. War never changes.' },
// ]

    // Removed the id key since it is automatically generated in mongoDB

// Ensure there is "db.categories.drop()" in seed.mongodb.js
// drop() method is a mongoDB method

await Category.deleteMany() // deleteMany is mongoose method
console.log('Deleted Categories')

await Category.insertMany(categories) // insertMany is mongoose method
console.log('Added Categories')

// await Entry.deleteMany() // deleteMany is mongoose method
// console.log('Deleted Entries')

// await Entry.insertMany(entries) // insertMany is mongoose method
// console.log('Added Entries')

// This is to disconnect the connection after running 'npm run seed' while server is running.
mongoose.disconnect()

